from django.shortcuts import render
from nltk.tokenize import word_tokenize

def index(request):
    return render(request, 'index.html')


stopwords = ['to',
             '.',
             'if',
             'which',
             'while',
             'in',
             'few',
             'their',
             'ourselves',
             'him',
             "isn't",
             "mightn't",
             "wouldn't",
             'our',
             'further',
             "doesn't",
             'after',
             'nor',
             'not',
             'so',
             'the',
             't',
             'what',
             'any',
             'more',
             "aren't",
             "didn't",
             'because',
             'has',
             "hadn't",
             'from',
             'have',
             'own',
             'how',
             'ain',
             'were',
             "mustn't",
             'they',
             'themselves',
             'we',
             'just',
             'of',
             'against',
             'won',
             'ours',
             'this',
             "shouldn't",
             'your',
             'then',
             'ma',
             'had',
             'myself',
             'each',
             'he',
             'only',
             "you'd",
             'these',
             "you've",
             'she',
             'haven',
             'here',
             'such',
             'do',
             'once',
             'o',
             'hasn',
             'you',
             'was',
             "wasn't",
             'some',
             's',
             'are',
             'is',
             "you're",
             'up',
             "hasn't",
             'can',
             'as',
             'y',
             'there',
             'same',
             'herself',
             'and',
             'all',
             "couldn't",
             'under',
             'with',
             'out',
             'those',
             'been',
             'before',
             'into',
             "you'll",
             'its',
             'who',
             'again',
             "should've",
             'but',
             'above',
             'it',
             'now',
             'most',
             'i',
             'down',
             'off',
             "that'll",
             'why',
             'doesn',
             'shouldn',
             'did',
             'between',
             'on',
             "weren't",
             'by',
             'below',
             'hadn',
             'isn',
             'didn',
             'through',
             'shan',
             "needn't",
             'needn',
             'them',
             'that',
             'weren',
             'very',
             'don',
             'for',
             'be',
             'aren',
             'her',
             're',
             'itself',
             'whom',
             'until',
             "it's",
             'doing',
             'no',
             'yours',
             've',
             "she's",
             'yourself',
             'having',
             'at',
             "haven't",
             'other',
             'his',
             'does',
             'will',
             'mightn',
             'yourselves',
             'both',
             'being',
             'wouldn',
             'theirs',
             'a',
             'himself',
             'd',
             'wasn',
             "won't",
             "shan't",
             'my',
             'about',
             'during',
             'than',
             'an',
             'hers',
             "don't",
             'over',
             'or',
             'me',
             'll',
             'am',
             'where',
             'couldn',
             'should',
             'too',
             'm',
             'mustn',
             'when']


def getDoc(document):
    d = []
    for doc in document:
        d.append(formatting(doc))
    return d


def remove_stopwords(text, stopwords):
    useful = [w for w in text if w not in stopwords]
    return useful


def formatting(document):
    words = word_tokenize(document)
    useful_words = remove_stopwords(words, stopwords)
    print(useful_words)


formatting("hi my name is kartikeya. I am a good person")
